-- ========================================================================
-- SUPPORT LINK BOX (Submit • Support • Grow)
-- PRODUCTION SUPABASE POSTGRESQL DATABASE SCHEMA & ROW LEVEL SECURITY (RLS)
-- ========================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------------------
-- 1. ENUMS & CUSTOM TYPES
-- ------------------------------------------------------------------------
CREATE TYPE member_status_enum AS ENUM ('ACTIVE', 'INACTIVE', 'FROZEN', 'SUSPENDED', 'REMOVED');
CREATE TYPE notice_type_enum AS ENUM ('GENERAL', 'WARNING', 'IMPORTANT', 'EMERGENCY');
CREATE TYPE warning_severity_enum AS ENUM ('SIMPLE', 'ALERT', 'KICKOUT');
CREATE TYPE report_category_enum AS ENUM ('WRONG_LINK', 'WRONG_INSTRUCTION', 'MEMBER_PROBLEM', 'TECHNICAL_PROBLEM', 'OTHER');
CREATE TYPE report_status_enum AS ENUM ('PENDING', 'RESOLVED', 'DISMISSED');
CREATE TYPE ad_position_enum AS ENUM ('TOP_BANNER', 'DASHBOARD', 'TODAYS_LINKS', 'LEADERBOARD', 'BETWEEN_CONTENT', 'FOOTER');
CREATE TYPE revenue_source_enum AS ENUM ('sponsor_direct', 'ad_network', 'affiliate', 'donation', 'saas_subscription');

-- ------------------------------------------------------------------------
-- 2. PROFILES & ROLES (Tied to Supabase Auth.users)
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    display_name TEXT NOT NULL,
    avatar_url TEXT,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------
-- 3. MEMBERS TABLE (Community Members Directory)
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.members (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    member_id INT UNIQUE GENERATED BY DEFAULT AS IDENTITY (START WITH 101),
    name TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    email TEXT,
    profile_photo TEXT,
    facebook_profile_url TEXT NOT NULL,
    status member_status_enum DEFAULT 'ACTIVE',
    join_date TIMESTAMPTZ DEFAULT NOW(),
    last_active TIMESTAMPTZ DEFAULT NOW(),
    total_links INT DEFAULT 0,
    total_supports INT DEFAULT 0,
    total_points INT DEFAULT 0,
    current_rank INT DEFAULT 0,
    current_streak INT DEFAULT 0,
    warning_count INT DEFAULT 0,
    frozen_reason TEXT,
    frozen_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    frozen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_members_status ON public.members(status);
CREATE INDEX idx_members_last_active ON public.members(last_active);
CREATE INDEX idx_members_points ON public.members(total_points DESC);

-- ------------------------------------------------------------------------
-- 4. WEEKLY SESSIONS
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.weekly_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    week_number INT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT FALSE,
    is_archived BOOLEAN DEFAULT FALSE,
    total_submissions INT DEFAULT 0,
    champion_member_id UUID REFERENCES public.members(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------
-- 5. DAILY LINKS (Submissions)
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.daily_links (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    link_number INT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    week_number INT NOT NULL,
    member_id UUID NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    facebook_post_url TEXT NOT NULL,
    instruction TEXT DEFAULT 'React + Comment',
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    is_valid BOOLEAN DEFAULT TRUE,
    total_received_supports INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_daily_member_submission UNIQUE (date, member_id)
);

CREATE INDEX idx_daily_links_date ON public.daily_links(date);
CREATE INDEX idx_daily_links_member ON public.daily_links(member_id);

-- ------------------------------------------------------------------------
-- 6. SUPPORT RECORDS (Tracking Member Support on Links)
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.support_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    supporter_member_id UUID NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    target_link_id UUID NOT NULL REFERENCES public.daily_links(id) ON DELETE CASCADE,
    completed_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'COMPLETED',
    CONSTRAINT unique_member_support_per_link UNIQUE (supporter_member_id, target_link_id)
);

CREATE INDEX idx_support_records_date_supporter ON public.support_records(date, supporter_member_id);
CREATE INDEX idx_support_records_link ON public.support_records(target_link_id);

-- ------------------------------------------------------------------------
-- 7. NOTICES & ANNOUNCEMENTS
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type notice_type_enum DEFAULT 'GENERAL',
    published_date TIMESTAMPTZ DEFAULT NOW(),
    priority INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------
-- 8. MEMBER WARNINGS
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.warnings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    member_id UUID NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    severity warning_severity_enum DEFAULT 'SIMPLE',
    reason TEXT NOT NULL,
    issued_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    issued_at TIMESTAMPTZ DEFAULT NOW(),
    is_acknowledged BOOLEAN DEFAULT FALSE
);

-- ------------------------------------------------------------------------
-- 9. MEMBER PROBLEM REPORTS
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reports (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    reporter_member_id UUID NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
    target_link_id UUID REFERENCES public.daily_links(id) ON DELETE SET NULL,
    category report_category_enum NOT NULL,
    description TEXT NOT NULL,
    screenshot_url TEXT,
    status report_status_enum DEFAULT 'PENDING',
    admin_notes TEXT,
    resolved_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------
-- 10. ADVERTISEMENTS & SPONSORS (Monetization Engine)
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.advertisements (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    banner_image TEXT NOT NULL,
    destination_url TEXT NOT NULL,
    position ad_position_enum DEFAULT 'DASHBOARD',
    status TEXT DEFAULT 'ACTIVE',
    priority INT DEFAULT 1,
    impressions INT DEFAULT 0,
    clicks INT DEFAULT 0,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.sponsors (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    logo_url TEXT NOT NULL,
    banner_url TEXT,
    website_url TEXT NOT NULL,
    campaign_title TEXT NOT NULL,
    position TEXT DEFAULT 'LEADERBOARD',
    status TEXT DEFAULT 'ACTIVE',
    impressions INT DEFAULT 0,
    clicks INT DEFAULT 0,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.affiliate_campaigns (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    commission_rate TEXT NOT NULL,
    affiliate_url TEXT NOT NULL,
    clicks INT DEFAULT 0,
    conversions INT DEFAULT 0,
    earned_bdt NUMERIC(12, 2) DEFAULT 0.00,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.revenue_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date DATE DEFAULT CURRENT_DATE,
    source revenue_source_enum NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    notes TEXT,
    reference TEXT,
    logged_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------
-- 11. AUDIT LOGS (Immutable Administrative Action History)
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    admin_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    admin_name TEXT NOT NULL,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    details TEXT NOT NULL
);

CREATE INDEX idx_audit_logs_timestamp ON public.audit_logs(timestamp DESC);

-- ------------------------------------------------------------------------
-- 12. SYSTEM SETTINGS
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.system_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ========================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advertisements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sponsors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revenue_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Helper function to check if current user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND is_admin = TRUE
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 1. Profiles RLS
CREATE POLICY "Public profiles are readable by authenticated users"
ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can update own profile"
ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Members RLS
CREATE POLICY "Active members directory readable by all authenticated"
ON public.members FOR SELECT USING (status != 'REMOVED' OR public.is_admin());

CREATE POLICY "Admins can insert or update members"
ON public.members FOR ALL USING (public.is_admin());

-- 3. Daily Links RLS
CREATE POLICY "Daily links viewable by active members"
ON public.daily_links FOR SELECT USING (true);

CREATE POLICY "Members can submit their own daily link"
ON public.daily_links FOR INSERT WITH CHECK (
    auth.uid() IN (SELECT user_id FROM public.members WHERE id = member_id)
    OR public.is_admin()
);

CREATE POLICY "Admins can modify all daily links"
ON public.daily_links FOR ALL USING (public.is_admin());

-- 4. Support Records RLS
CREATE POLICY "Support records viewable by members"
ON public.support_records FOR SELECT USING (true);

CREATE POLICY "Members can mark own support"
ON public.support_records FOR INSERT WITH CHECK (
    auth.uid() IN (SELECT user_id FROM public.members WHERE id = supporter_member_id)
    OR public.is_admin()
);

-- 5. Notices, Ads, Sponsors (Public read, admin write)
CREATE POLICY "Public read notices" ON public.notices FOR SELECT USING (is_active = true OR public.is_admin());
CREATE POLICY "Admin write notices" ON public.notices FOR ALL USING (public.is_admin());

CREATE POLICY "Public read ads" ON public.advertisements FOR SELECT USING (status = 'ACTIVE' OR public.is_admin());
CREATE POLICY "Admin write ads" ON public.advertisements FOR ALL USING (public.is_admin());

CREATE POLICY "Public read sponsors" ON public.sponsors FOR SELECT USING (status = 'ACTIVE' OR public.is_admin());
CREATE POLICY "Admin write sponsors" ON public.sponsors FOR ALL USING (public.is_admin());

-- 6. Audit logs (Admin only)
CREATE POLICY "Admin view audit logs" ON public.audit_logs FOR SELECT USING (public.is_admin());
CREATE POLICY "Admin insert audit logs" ON public.audit_logs FOR INSERT WITH CHECK (public.is_admin());

-- ========================================================================
-- END OF SCHEMA
-- ========================================================================
